version: '3'

services:
  react-dist:
    image: waretrack/dist
    environment:
      VIRTUAL_HOST: 'waretrack.co'
      VIRTUAL_PORT: '80'
      LETSENCRYPT_HOST: 'waretrack.co'
      LETSENCRYPT_EMAIL: 'moren1viguel@gmail.com'
    volumes:
      - ./my_custom_config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "5173:80"
    networks:
        - default
        - nginx_proxy

networks:
  default:
  nginx_proxy:
    external: true
